### ISSUE TITLE
Метод containsGame в GameStore не находит последнюю игру в каталоге

### ISSUE THREAD

**Issue by Uwenta** [russo2100/javaqa-team-diplom#1]
# Описание

Метод containsGame в GameStore должен возвращать true, если игра есть в каталоге. 
Но метод не находит последнюю игру в списке. Если игра всего одна, то он ее тоже не находит.
Остальные игры находит. Если игр нет совсем в каталоге - это отражается верно.
Ошибка в условии цикла, должно быть i <= games.size(),

# Локация дефекта

https://github.com/russo2100/javaqa-team-diplom/blob/bed38f5a7246954ec1abce063c966ff317e8ff55/src/main/java/ru/netology/GameStore.java#L33

# Шаги воспроизведения

1. Открыть [код программы тестирования GameStore](https://github.com/russo2100/javaqa-team-diplom/blob/bed38f5a7246954ec1abce063c966ff317e8ff55/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.  Запустить тест shouldContainsLostGame
3.  Посмотреть результат тестирования в консоли

*Ожидаемый результат:* тест прошел
*Фактический результат:* тест не прошел

# Скриншот

![2022-07-18_16-43-28](https://user-images.githubusercontent.com/103641997/179509450-a4e8960b-6cda-4d99-828d-2f882cf52622.png)

# Окружение
* **Операционная система:** Microsoft Windows 10.0
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by russo2100** [comment]
# Исправление
![image](https://user-images.githubusercontent.com/100371429/179730316-d9a815d6-1707-4b65-a956-328685b6e09b.png)

* Ожидаемый результат 
Тест прошел
* Фактический результат
Тест прошел

# Окружение
* **Windows 10 Pro**
* **IntelliJ IDEA 2021.3.2 (Community Edition)**
* **Java JDK 11**
