### ISSUE TITLE
Метод getMostPlayer в GameStore возвращает null, если время игры у лучшего игрока - 1

### ISSUE THREAD

**Issue by Uwenta** [russo2100/javaqa-team-diplom#2]
# Описание

Метод getMostPlayer в GameStore возвращает null, если время у лучшего игрока - 1 час.
Начальное значение переменной mostTime должно быть равно 0

# Локация дефекта

https://github.com/russo2100/javaqa-team-diplom/blob/bed38f5a7246954ec1abce063c966ff317e8ff55/src/main/java/ru/netology/GameStore.java#L59

# Шаги воспроизведения

1. Открыть [код программы тестирования GameStore](https://github.com/russo2100/javaqa-team-diplom/blob/bed38f5a7246954ec1abce063c966ff317e8ff55/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.  Запустить тест shouldGetMostPlayerOneHour
3.  Посмотреть результат тестирования в консоли

*Ожидаемый результат:* тест прошел
*Фактический результат:* тест не прошел

# Скриншот
![oneHour](https://user-images.githubusercontent.com/103641997/179529131-a1f0da33-9a89-42d3-8e49-2b965390ec12.png)

# Окружение
* **Операционная система:** Microsoft Windows 10.0
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by russo2100** [comment]
Исправлено и закрыто
