### ISSUE TITLE
Метод sumGenry не суммирует время проигранное в определенный жанр

### ISSUE THREAD

**Issue by russo2100** [russo2100/javaqa-team-diplom#3]
# Описание

Метод sumGenry не суммирует время проигранное в определенный жанр

# Локация дефекта
https://github.com/russo2100/javaqa-team-diplom/blob/1d10ad0ee95d0612200e5bcc505d133c66348472/src/main/java/ru/netology/Player.java#L45

# Шаги воспроизведения
1. Открыть [Код программы тестирования] (https://github.com/russo2100/javaqa-team-diplom/blob/1d10ad0ee95d0612200e5bcc505d133c66348472/src/test/java/ru/netology/PlayerTest.java) в IDEA
2. Запустить ТЕСТ shouldSumGenreIfOneGame
3. Посмотреть результат тестирования в консоли

![image](https://user-images.githubusercontent.com/100371429/179538724-128e8d06-c840-4895-9256-d338d85bb694.png)

* Ожидаемый результат: 
Тест прошел
* Фактический результат:
Тест не прошел 

# Окружение
Windows 10 Pro
IntelliJ IDEA 2021.3.2 (Community Edition)
JDK 11

**Comment by Uwenta** [comment]
Откорректирован также метод play, тест проходит
