### ISSUE TITLE
Метод getSumPlayedTime в GameStore не написан, возвращает всегда 0

### ISSUE THREAD

**Issue by Uwenta** [russo2100/javaqa-team-diplom#5]
# Описание

Метод getSumPlayedTime в GameStore не написан, возвращает всегда 0
Метод должен считать общее количество времени всех игроков, проведенного за играми этого каталога

# Локация дефекта

https://github.com/russo2100/javaqa-team-diplom/blob/bed38f5a7246954ec1abce063c966ff317e8ff55/src/main/java/ru/netology/GameStore.java#L75

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/russo2100/javaqa-team-diplom/blob/bed38f5a7246954ec1abce063c966ff317e8ff55/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.  Запустить тест shouldGetSumPlayedTime
3.  Посмотреть результат тестирования в консоли

*Ожидаемый результат:* тест прошел
*Фактический результат:* тест не прошел

# Скриншоты

![summ](https://user-images.githubusercontent.com/103641997/179546637-9ec60ea1-06e4-4855-b784-836a822305fa.png)
![summ2](https://user-images.githubusercontent.com/103641997/179546653-b6c49988-0f76-4dfc-ab4b-38acec21da8b.png)

# Окружение

* **Операционная система:** Microsoft Windows 10.0
* **IDE:** IntelliJ IDEA 2020.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by russo2100** [comment]
Исправлено
