### ISSUE TITLE
Метод sumGenre не суммирует время

### ISSUE THREAD

**Issue by russo2100** [russo2100/javaqa-team-diplom#7]
# Описание
Метод sumGenre не суммирует время проигранное во все игры заданного жанра. Возвращает 0.

# Локация дефекта

https://github.com/russo2100/javaqa-team-diplom/blob/1d10ad0ee95d0612200e5bcc505d133c66348472/src/main/java/ru/netology/Player.java#L45

# Шаги воспроизведения
Открыть [Код программы тестирования] (https://github.com/russo2100/javaqa-team-diplom/blob/1d10ad0ee95d0612200e5bcc505d133c66348472/src/test/java/ru/netology/PlayerTest.java) в IDEA.
Запустить ТЕСТ shouldSumGenreIfGameReplay
Посмотреть результат тестирования в консоли:
![image](https://user-images.githubusercontent.com/100371429/179666224-94898d5c-39ab-4879-a5cf-b4a51173cc0b.png)

* Ожидаемый результат
6
* Фактический результат
0

# Окружение
* **Windows 10 Pro**
* **IntelliJ IDEA 2021.3.2 (Community Edition)**
* **Java JDK 11**

**Comment by Uwenta** [comment]
Тест проходит после закрытия других багов
